apiVersion: v1
kind: Namespace
metadata:
  name: devsecops
  labels:
    # Pod Security Admission: reject any pod that is not "restricted"-compliant
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
