# BROKEN: the developer generated the value with   echo "dummy-pass-123" | base64
# -> ZHVtbXktcGFzcy0xMjMK   (the trailing "K" encodes a hidden \n newline byte 0x0a)
apiVersion: v1
kind: Secret
metadata:
  name: yatri-app-db-secret
type: Opaque
data:
  DB_USER: eWF0cmlfYWRtaW4=
  DB_PASSWORD: ZHVtbXktcGFzcy0xMjMK
